services:
  app:
    image: k4na/daylight:latest
    container_name: daylight_app
    restart: unless-stopped
    env_file:
    - .env
    ports:
    - "8083:80"
    volumes:
    - ./storage/app/data:/var/www/html/storage/app/data
volumes:
  daylight_storage:
  daylight_data:
